GuardianReviews.Web/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GuardianReviews.ApplicationServices;
using GuardianReviews.Domain.BaseClasses;
using GuardianReviews.Domain.Interfaces;
using GuardianReviews.Domain.Model;
using GuardianReviews.Web.Models;

namespace GuardianReviews.Web.Controllers
{
    public class MenuController : Controller
    {
        private readonly IUserRepository _userRepository;

        public MenuController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }


        [ChildActionOnly]
        public ActionResult Index()
        {
            var user = _userRepository.GetUserByEmail(User.Identity.Name);
            
            var home = new MenuItemViewModel { DisplayName = "Home", Css = GetCss("Home"), Closeable=false, Link = "/" };
            
            var items = new[] { home }.Concat(GetReviewMenuItems(user));

            if (user != null)
                items = items.Concat(new[]{new MenuItemViewModel { DisplayName = "Settings", Css = GetCss("Settings"), Closeable=false, Link = "/user/settings" }});
            
            return View("_MenuPartial", items);
        }
        private IEnumerable<MenuItemViewModel> GetReviewMenuItems(User user)
        {
            var items = Enumeration.GetAll<ReviewTypes>().Where(r => r.ShowInUI);
            
            if (user != null)
                items = items.Where(user.IsSubscribedTo);
            
            return items.Select(i => MenuItemFromReviewType(i, user != null)).ToList();
        }
        private MenuItemViewModel MenuItemFromReviewType(ReviewTypes reviewType, bool closeable)
        {
            return new MenuItemViewModel
                       {
                           DisplayName = reviewType.DisplayName,
                           Name = reviewType.Name,
                           Link = Url.Action("Index", "Review", new {reviewType = reviewType.Name}),
                           Css = GetCss(reviewType.Name),
                           Closeable = closeable
                       };
        }
        private string GetCss(string displayName)
        {
            if (TabIsActive(displayName))
                return "ui-tabs-selected ui-state-active";
            return "";
        }
        private bool TabIsActive(string tabName)
        {
            switch (tabName)
            {
                case "Home":
                    return ControllerAndActionEquals<HomeController>("Index");
                case "Settings":
                    return ControllerAndActionEquals<UserController>("Settings");
                default:
                    return ControllerAndActionEquals<ReviewController>("Index") &&
                           RouteData.Values["reviewType"].ToString() == tabName;
            }
        }
        private bool ControllerAndActionEquals<TController>(string actionName)
        {
            return ControllerContext.ParentActionViewContext.Controller.GetType() == typeof(TController) &&
                   ControllerContext.ParentActionViewContext.RouteData.Values["action"].ToString() == actionName;
        }

    }
}

GuardianReviews.Web/Controllers/UserController.cs
using GuardianReviews.ApplicationServices;
using System.Web.Mvc;
using System.Web.Security;
using GuardianReviews.Domain.Interfaces;
using GuardianReviews.Domain.Model;
using Newtonsoft.Json;
using SharpArch.Web.NHibernate;
using SharpArch.Web.JsonNet;
using System.Linq;
namespace GuardianReviews.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IOpenIdService _openIdService;
        private readonly IUserRepository _userRepository;

        public UserController(IOpenIdService openIdService, IUserRepository userRepository)
        {
            _userRepository = userRepository;
            _openIdService = openIdService;
        }

        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                Response.Redirect("~/User/Login?ReturnUrl=Index");
            }

            return View("Index");
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return Redirect("~/Home");
        }

        public ActionResult LogIn()
        {
            // Stage 1: display login form to user
            return View("Login");
        }

        [ValidateInput(false)]
        public ActionResult Authenticate(string returnUrl)
        {
            return _openIdService.Authenticate(Request.Form["openid_identifier"], returnUrl);
        }
        public ActionResult Settings()
        {
            var user = GetUser();
            
            return View(user);
        }
        [Transaction]
        public ActionResult ExcludeReviewType(ReviewTypes id)
        {
            var user = GetUser();
            if(user != null)
                user.UnsubscribeFrom(id);
            return new RedirectResult(Request.UrlReferrer != null ? Request.UrlReferrer.ToString() : "/");
        }
        [Transaction]
        public ActionResult SaveReview(int id)
        {
            _userRepository.SaveReviewToList(User.Identity.Name, id);
            return new RedirectResult(Request.UrlReferrer != null ? Request.UrlReferrer.ToString() : "/");
        }
        [Transaction]
        public ActionResult RemoveReview(int id)
        {
            _userRepository.RemoveReviewFromList(User.Identity.Name, id);
            return new RedirectResult(Request.UrlReferrer != null ? Request.UrlReferrer.ToString() : "/");
        }
        public ActionResult MyList(HttpResponseTypes format = HttpResponseTypes.Html)
        {
            var user = GetUser();
            if (user == null)
                return new EmptyResult();
            
            if(format == HttpResponseTypes.Html)
                return View(user.SavedReviews.OrderByDescending(r =>r.DateAdded).ToArray());
            
            return new JsonNetResult(user.SavedReviews);
        }

        private User GetUser()
        {
            if (!User.Identity.IsAuthenticated)
                return null;
            return _userRepository.GetUserByEmail(User.Identity.Name);

        }

    }
}

GuardianReviews.Web/Views/Shared/_Base.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@View.Title</title>
    <link href="@Url.Content("~/Content/Css/smoothness/jquery-ui-1.8.6.custom.css")" rel="stylesheet" type="text/css" />
    
    <link href="@Url.Content("~/Content/Css/Site.css")" rel="stylesheet" type="text/css" />
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.4.1.js" type="text/javascript"></script>
    @*<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.4.1.vsdoc.js" type="text/javascript"></script>*@
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.6/jquery-ui.js" type="text/javascript"></script>
    @*    
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    *@
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>
                    <a href="/"><img src="/Content/images/Logo.png" alt="Review Queue logo" /></a></h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
        </div>
        <div id="page">
            @RenderBody()
        </div>
    </div>
</body>
</html>

GuardianReviews.Web/Views/Shared/_Layout.cshtml
@using GuardianReviews.Domain.Model
@using GuardianReviews.Domain.BaseClasses
@{
    Layout = Layout = "~/Views/Shared/_Base.cshtml";
}
@*<div id="menucontainer">
    <ul id="menu">
        <li><span><a href="/review" title="content">All</span></a></li>
        @foreach (var reviewType in Enumeration.GetAll<ReviewTypes>().Where(r => r.ShowInUI))
        {
            <li><span><a href="/review/@reviewType.Name" title="content">@reviewType.DisplayName
            </a></span></li>
        }
        <li><span><a href="/review" title="content">Settings</span></a></li>
    </ul>*@

    @{Html.RenderAction("Index", "Menu");}
    <div id="main">
        @RenderBody()
    </div>
@*</div>*@
@*<script type="text/javascript">
    $(function () {
        $("#menucontainer").tabs();
    });
</script>
*@

GuardianReviews.Web/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>
    [ @Html.ActionLink("Log Off", "LogOut", "User") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogIn", "User") ]
}

GuardianReviews.Web/Views/Shared/_MenuItemPartial.cshtml
@model dynamic
@using GuardianReviews.Web.Helpers
<li class="ui-state-default ui-corner-top @MenuHelper.GetMenuTabCss(Html, @Model.TabName)">
    <span>
        @Model.Link
    </span>
</li>

GuardianReviews.Web/Views/Shared/_MenuPartial.cshtml
@{  
    Layout = null;  
} 
@model IEnumerable<MenuItemViewModel>
<div id="menucontainer" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
    <ul id="menu" class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
        @foreach (var item in Model)
        {
            <li class="ui-state-default ui-corner-top @item.Css"> 
                <span>
                    <a href="@item.Link">@item.DisplayName</a> 
                    @if (item.Closeable)
                    { 
                        <a class="no-padding" href="/user/ExcludeReviewType/@item.Name"><img src="/Content/images/close.jpg" title="Close this tab" alt="Close the @item.DisplayName tab" /></a>
                    }
                    
                </span>
            </li>
        }
    </ul>
    <div id="content" class="ui-tabs-panel ui-widget-content ui-corner-bottom">
    </div>

GuardianReviews.Web/Views/Shared/_ReviewList.cshtml
@model List<Review>
@*<script src="@Url.Content("~/Scripts/jquery-1.4.1-vsdoc.js")" type="text/javascript"></script>*@
<div id="review-list">
<ul>
    @foreach (var review in Model)
    {
        <li>
            <img src="@(review.Thumbnail != null ? review.Thumbnail : "Content/Images/" + review.ReviewType.Name + ".png")" />
            <h3>@review.Title.Html()</h3>
            <em>@review.PublicationDate.ToLongDateString()</em>
            <p>@review.TrailText.Html()</p>
            <div class="star-rating-@review.StarRating"></div>
            @if (User.Identity.IsAuthenticated)
            {
                <a href='/user/saveReview/@review.Id' >Save to my list</a>
            }<br />
            <a href='/review/view/@review.Id' id="readReviewLink" >Read the whole review...</a>
        </li>   
    }
</ul>
</div>
<script src="@Url.Content("~/Scripts/jquery.raty.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    for (var i = 1; i < 6; i++) {
        if ($('.star-rating-' + i).length > 0) {
            $('.star-rating-' + i).raty({
                readOnly: true,
                start: i,
                path: '/Content/Images'
            });
        }
    }
    function saveToList(reviewId)
    {
        $.get("/user/savereview/" + reviewId, null, function (responseText, textStatus) {

        }, "html");
    }
</script>